- name: Install node
  uses: actions/setup-node@v4
  with:
    node-version: '22'
- uses: jorelali/setup-elm@v6
  with:
    elm-version: 0.19.1
- name: Compile elm to js
  run: |
    cd client/deps
    elm make src/Deps.elm --optimize --output ../../src/server/deployments/client/assets/js/deps.js
