name: back-compat-pr

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  back-compat-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Install elm
        uses: ./.github/install-elm
      - name: Build main
        run: cargo build --target-dir /var/tmp/main
      - name: Add profile with ecscope on main
        run: /var/tmp/main/debug/ecscope profiles add prof1
      - uses: actions/checkout@v4
      - name: Compile elm to js
        uses: ./.github/compile-elm
      - name: Build head
        run: cargo build --target-dir /var/tmp/head
      - name: Run ecscope on head
        run: /var/tmp/head/debug/ecscope monitor prof1 --debug
