name: build

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "*Cargo.*"
      - "**/*.rs"
      - ".github/workflows/build.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install elm
        run: |
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          rm elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          cd client
          elm make src/Deps.elm --output ../../src/server/deployments/client/assets/js/deps.js
      - name: Build
        run: cargo build
