name: build

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "*Cargo.*"
      - "**/*.rs"
      - ".github/workflows/build.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Compile elm to js
        run: |
          cd client/deps
          elm make src/Deps.elm --optimize --output ../../src/server/deployments/client/assets/js/deps.js
      - name: Build
        run: cargo build
