name: lint

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "*Cargo.*"
      - "**/*.rs"
      - ".github/workflows/lint.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy

  lint-gleam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.1"
          rebar3-version: "3"
      - name: Compile gleam to js
        run: |
          cd src/server/deployments/client
          gleam deps download
          gleam format src --check
