name: lint

on:
  push:
    branches: ["main"]
  pull_request:
    paths:
      - "*Cargo.*"
      - "**/*.rs"
      - ".github/workflows/lint.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Compile elm to js
        run: |
          cd client/deps
          elm make src/Deps.elm --optimize --output ../../src/server/deployments/client/assets/js/deps.js
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy

  lint-elm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install elm-format
        uses: jaxxstorm/action-install-gh-release@4304621e8c48d66093a8a214af5d5b5bc3b3d943
        with:
          repo: avh4/elm-format
          tag: 0.8.7
      - name: Check formatting
        run: |
          cd client/deps
          elm-format --validate src
